name: vscode-example
channels:
  - conda-forge
dependencies:
  - python >= 3.6
  - pip
  - cmake >= 3.15
  - make
  - gxx >= 11.2
  - gdb
  - numpy
  - pandas
  - matplotlib
  - plotnine
  - ipykernel
  - jupyter
  - docker
